[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "crystalgnns"
version = "0.0.1"
requires-python = ">=3.7"
dependencies = [
        'networkx',
        'tensorflow==2.11',
        'pymatgen',
        'pyxtal',
        'kgcnn'
]
